name: Deploy to AWS EC2

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull & Restart service on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USER }}/mabinogi-rice-collector
            git pull origin main

            pip install -r requirements.txt

            sudo systemctl restart mabinogi
            echo "▶ mabinogi.service restarted"
